Expose additional fields
kit-sdq/artemis4j pull request #24
Opened 2023-10-30 16:04 UTC by moritzhertler

2023-10-30 21:21 UTC, dfuchss requested changes

2023-10-30 21:21 UTC, dfuchss commented on src/main/java/edu/kit/kastel/sdq/artemis4j/api/artemis/assessment/Submission.java
> +	public boolean hasBuildFailed() {
Would isBuildFailed fit better ?

2023-10-31 14:06 UTC, moritzhertler commented on src/main/java/edu/kit/kastel/sdq/artemis4j/api/artemis/assessment/Submission.java
> +	public boolean hasBuildFailed() {
Sure.

2023-10-31 14:28 UTC, dfuchss approved these changes

2023-10-31 14:28 UTC, merged